config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'widgets#index'
  resources :widgets, only: [:index]

  resources :users, only: [:new, :create, :show, :edit, :update, :edit_passwords, :update_passwords] do
    get 'password', to: 'users#edit_passwords'
    patch 'password', to: 'users#update_passwords'
    resources :widgets, only: [:index, :new, :create, :update, :destroy]
  end

  get 'login', to:'auth#new'
  post 'login', to:'auth#create'
  delete 'logout', to:'auth#destroy'
  get 'forgot_password', to: 'auth#edit'
  put 'forgot_password', to: 'auth#update'
end

app/models/user.rb
class User < ShowoffRecord
  include Auth

  attr_accessor :id, :email, :name, :images, :first_name, :last_name, :date_of_birth,
                :password, :password_confirmation, :image_url,
                :access_token, :refresh_token, :expires_in, :authentication_token_expires_at,
                :current_password, :active

  validates_length_of :password, minimum: 8, on: [:create_user, :update_password]
  validates_presence_of :email, :first_name, :last_name, :password, :password_confirmation, on: :create_user
  validate :passwords_equality, on: [:create_user, :update_password]
  validates_presence_of :first_name, :last_name, :date_of_birth, on: :update_user

  def attributes
    {
        id: id,
        email: email,
        last_name: last_name,
        first_name: first_name,
        image_url: image_url,
        password: password,
        date_of_birth: date_of_birth
    }
  end

  def auth_attributes
    {
        last_name: last_name,
        first_name: first_name,
        id: id,
        email: email,
        access_token: access_token,
        refresh_token: refresh_token,
        expires_in: expires_in,
        authentication_token_expires_at: authentication_token_expires_at
    }
  end

  def create!(authenticate_after: true)
    return self unless valid?(:create_user)
    response = ShowoffService::User.create attributes
    if response["code"] != 0
      self.errors.add :base, response["message"]
    else
      set_auth_tokens response["data"]["token"] if authenticate_after
    end
    self
  end


  def update!(attr)
    self.attributes = attr
    return self unless valid?(:update_user)
    response = ShowoffService::User.update attr
    if response["code"] != 0
      self.errors.add :base, response["message"]
    end
    self
  end

  def update_password!
    return self unless valid?(:update_password)
    response = ShowoffService::User.update_password current_password, password
    if response.nil? || (response.present? && response["code"] != 0)
      self.errors.add :base, "Invalid Password, please enter again"
    else
      set_auth_tokens response["data"]["token"]
    end
    self
  end

  def full_name
    name || "#{first_name}  #{last_name}"
  end

  def self.find(id)
    response = ShowoffService::User.find(id)
    raise RecordNotFound if response.nil?
    User.new response["data"]["user"]
  end

  private

  def passwords_equality
    errors.add(:password_confirmation,
               "Passwords doesnt match") unless password == password_confirmation
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, except: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update,:edit_passwords, :update_passwords ]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.create!
    @error = @user.errors.any?
    @messages = @error ? @user.errors.full_messages : ["User Successfully created"]
    set_session @user unless @error
  end

  def edit
    add_breadcrumb "PROFILE", user_path('me')
  end

  def update
    @user.update! user_update_params
    set_session @user, merge: true
    flash[:success] = "Successfully updated your profile"
    redirect_to user_path('me')
  end

  def edit_passwords
    add_breadcrumb "PROFILE", user_path('me')
  end

  def update_passwords
    @user.attributes = password_params
    @user.update_password!
    if @user.errors.any?
      flash.now[:notice] =  @user.errors.full_messages
      render :edit_passwords
    else
      flash[:success] = "Password successfully updated"
      redirect_to user_path 'me'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :image_url)
  end

  def user_update_params
    params.require(:user).permit(:first_name, :last_name, :image_url, :date_of_birth)
  end

  def update_password_params

  end

  def set_user
    @user = User.find(params[:id] || params[:user_id])
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation, :current_password)
  end

end

app/views/users/_form.html.erb
<div class="modal-dialog  modal-dialog-centered modal-login">
  <div class="modal-content">
    <%= form_for @user, remote: true do |f| %>
      <div class="modal-header">
        <h4 class="modal-title">Register</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>

      <div class="modal-body">

        <div class="form-group">
          <%= f.label :first_name, "First Name" %>
          <%= f.text_field :first_name, class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :last_name, "Second Name" %>
          <%= f.text_field :last_name, class: "form-control", required: true %>
        </div>


          <div class="form-group">
            <%= f.label :email, "Email" %>
            <%= f.email_field :email, class: "form-control", required: true %>
          </div>

          <div class="form-group">
            <%= f.label :password, "password" %>
            <%= f.password_field :password, class: 'form-control', required: true %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, "Confirm Password" %>
            <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
          </div>


        <div class="form-group">
          <%= f.label :image_url, "Profile  URL" %>
          <%= f.url_field :image_url, class: 'form-control', required: true %>
        </div>


      </div>
      <div class="modal-footer">
        <%= submit_tag "Register", class: 'btn btn-primary btn-block' %>
        <%= link_to "Login", login_path, remote: true, class: 'btn btn-outline-primary btn-block' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/create.js.erb
<%= make_js_flashes @error, @messages  %>
<% if @unless %>
  window.location.reload()
<% end %>

app/views/users/edit.html.erb
<div class="card">

  <%= form_for @user do |f| %>


    <div class="card-body">

      <div class="form-group">
        <%= f.label :first_name, "First Name" %>
        <%= f.text_field :first_name, class: "form-control", required: true %>
      </div>

      <div class="form-group">
        <%= f.label :last_name, "Second Name" %>
        <%= f.text_field :last_name, class: "form-control", required: true %>
      </div>

      <div class="form-group">
        <%= f.label :image_url, "Profile  URL" %>
        <div class="row">
          <div class="col-2"><%= image_tag @user.images["original_url"], size: '100x100' %></div>
          <div class="col-10"><%= f.url_field :image_url, value: @user.images["original_url"], class: 'form-control', required: true %></div>
        </div>
      </div>


      <div class="form-group">
          <%= f.label :date_of_birth, "DOB" %>
            <%= f.text_field :date_of_birth,
                              class: 'form-control inline', required: true %>
      </div>


    </div>
    <div class="card-footer">
      <%= submit_tag "Save", class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>

</div>

app/views/users/edit_passwords.html.erb
<div class="card">

  <%= form_for @user, url: user_password_path  do |f| %>

    <div class="card-body">

      <div class="form-group">
        <%= f.label :current_password, "Old Password" %>
        <%= f.password_field :current_password, class: 'form-control', required: true %>
      </div>


      <div class="form-group">
        <%= f.label :password, "New Password" %>
        <%= f.password_field :password, class: 'form-control', required: true %>
      </div>


      <div class="form-group">
        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation, class: 'form-control', required: true %>
      </div>


    </div>

    <div class="card-footer">
      <%= submit_tag "Save", class: 'btn btn-primary btn-block' %>
    </div>
  <% end %>

</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/new.js.erb
var elem = $('#modal');
elem.html( "<%= j render 'form' %>")
elem.modal()

app/views/users/show.html.erb
<div class="card">
  <div class="card-body">
    <div class="row user-row">
      <div class="col-md-6 img">
        <%= image_tag @user.images["small_url"], size: '200x200' %>
      </div>
      <div class="col-md-6 details">
        <blockquote>
          <h5><%= @user.full_name %></h5>
          <small><cite title="Source Title"> </cite></small>
        </blockquote>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="row justify-content-between">
      <div class="col-2 d-flex">
        <%= link_to "LIST #{ current_user_resource? ? "MY" : "USER" } WIDGETS",
                    user_widgets_path(current_user_resource? ? 'me' : @user.id),
                    class: 'btn btn btn-outline-primary card-link' %>

        <%= link_to "CREATE WIDGETS",
                    new_user_widget_path(current_user_resource? ? 'me' : @user.id),
                    class: 'btn btn btn-primary card-link', remote: true if current_user_resource? %>

      </div>
      <div class="col-4 d-flex">
        <% if current_user_resource? %>
          <%= link_to "CHANGE PASSWORD", user_password_path('me'), class: 'btn btn btn-outline-primary card-link' %>
          <%= link_to "EDIT PROFILE", edit_user_path, class: 'btn btn btn-outline-primary card-link' %>
        <% end %>
      </div>
    </div>
  </div>
</div>