config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'widgets#index'
  resources :widgets, only: [:index]

  resources :users, only: [:new, :create, :show, :edit, :update, :edit_passwords, :update_passwords] do
    get 'password', to: 'users#edit_passwords'
    patch 'password', to: 'users#update_passwords'
    resources :widgets, only: [:index, :new, :create, :update, :destroy]
  end

  get 'login', to:'auth#new'
  post 'login', to:'auth#create'
  delete 'logout', to:'auth#destroy'
  get 'forgot_password', to: 'auth#edit'
  put 'forgot_password', to: 'auth#update'
end

app/views/shared/_flash.html.erb
<div class="d-none">

  <% if flash[:notice]  %>
    <% flash[:notice] = [ flash[:notice]] unless flash[:notice].is_a? Array %>
    <% flash[:notice].each do |message|  %>
      <div class="alert danger">
        <%= message %>
      </div>
    <% end %>
  <% end %>

  <% if flash[:success]  %>
    <% flash[:success] = [ flash[:success]] unless flash[:success].is_a? Array %>
    <% flash[:success].each do |message|  %>
      <div class="alert success">
        <%= message %>
      </div>
    <% end %>
  <% end %>

</div>

app/views/shared/_loader.html.erb
<div id="loader_backdrop">
  <div class="loader">
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "WIDGET GALLERY", root_path, class:'navbar-brand'  %>

  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto"></ul>
    <span class="navbar-text">
       <%= link_to "PROFILE", user_path('me'), class: 'btn btn-primary mr-4' if logged_in? && !profile_path?  %>
       <%= link_to "LOGIN", login_path, remote: true, class:'btn btn-primary'  unless logged_in? %>
       <%= link_to "LOGOUT", logout_path, method: :delete, class:'btn btn-outline-danger' if logged_in? %>
    </span>
  </div>
</nav>

app/views/shared/_search_bar.html.erb
<div class="col-12 mt-4 mb-4">
<%= form_with(method: "get", autocomplete: 'off',class:'form-horizontal', local: true) do %>
  <div class="input-group">
    <%= search_field_tag :term, params[:term] , class: 'form-control', placeholder: "Search" %>
    <span class="input-group-btn ml-2">
      <%= button_tag("Search", type: "submit", class: "btn btn-primary", name:'') %>
    </span>
  </div>
<% end %>
</div>