config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'widgets#index'
  resources :widgets, only: [:index]

  resources :users, only: [:new, :create, :show, :edit, :update, :edit_passwords, :update_passwords] do
    get 'password', to: 'users#edit_passwords'
    patch 'password', to: 'users#update_passwords'
    resources :widgets, only: [:index, :new, :create, :update, :destroy]
  end

  get 'login', to:'auth#new'
  post 'login', to:'auth#create'
  delete 'logout', to:'auth#destroy'
  get 'forgot_password', to: 'auth#edit'
  put 'forgot_password', to: 'auth#update'
end

app/models/widget.rb
class Widget < ShowoffRecord
  attr_accessor :name, :description, :kind, :user,
                :images, :id, :owner

  validates_presence_of :name, :description, :kind
  validates_inclusion_of :kind , in: %w(visible hidden), message: "value must me either visible / hidden"

  def attributes
    {
        kind: kind,
        name: name,
        description: description,
        owner: owner
    }
  end

  def self.all(user_id: nil, term: '')
    response = user_id ?
                   ShowoffService::Widget.user_all(user_id: user_id, search_term: term) :
                   ShowoffService::Widget.visible(term)
    widgets = []
    if response
      widgets = response["data"]["widgets"].map { |attrs| Widget.new(attrs) }
      widgets.map { |widget| widget.user = User.new(widget.user) }
    end
    widgets
  end

  def update!(attr)
    response = ShowoffService::Widget.update(id, attr)
    if response["code"] != 0
      self.errors.add :base, response["message"]
    end
    self
  end

  def destroy
    response = ShowoffService::Widget.destroy(id)
    if response["code"] != 0
      self.errors.add :base, response["message"]
    end
    self
  end

  def create!
    response = ShowoffService::Widget.create attributes
    if response["code"] != 0
      self.errors.add :base, response["message"]
    end
    self
  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController

  before_action :authenticate_user, except: [:index]
  before_action :set_widget, only: [:destroy, :update]

  def index
    if params[:user_id]
      add_breadcrumb "PROFILE", user_path(params[:user_id])
    end
    raise ShowoffClient::Error::UnauthorisedAccess if params[:user_id] && !logged_in?
    @widgets = Widget.all(user_id: params[:user_id], term: search_params)
  end

  def new
    @widget = Widget.new
    add_breadcrumb "PROFILE", user_path(params[:user_id])
  end

  def create
    @widget = Widget.new widget_params
    @widget.create!
    @error = @widget.errors.any?
    @messages = @error ? @widget.errors.full_messages : ["Widget Successfully created"]
  end

  def update
    @widget.update! widget_params
    @error = @widget.errors.any?
    @messages = @error ?  @widget.errors.full_messages : ["Widget Successfully updated"]
  end

  def destroy
    @widget.destroy
    if @widget.errors.any?
      flash[:success] = "Widget deleted Successfully "
    else
      flash[:notice] = @widget.errors.full_messages
    end
    redirect_back(fallback_location: root_path)
  end

  private

  def search_params
    params[:term]
  end

  def widget_params
    params.require(:widget).permit(:name, :description, :kind)
  end

  def set_widget
    @widget = Widget.new(id: params[:id])
  end

end

app/views/widgets/_form.html.erb
<% widget = @widget || widget %>
<div class="modal-dialog  modal-dialog-centered modal-login">
  <div class="modal-content">

    <%= form_for widget, url: ( widget.persisted? ? user_widget_path(current_user.id, widget.id) : user_widgets_path(current_user.id) ),
                 method: (widget.persisted? ? :patch : :post),
                 remote: true do |f| %>

      <div class="modal-header">
        <h4 class="modal-title">
          <% if widget.persisted? %>
            EDIT
          <% else %>
            CREATE
          <% end %>

          WIDGET
        </h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      </div>

      <div class="modal-body">

        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :description, "Description" %>
          <%= f.text_area :description, class: "form-control", required: true %>
        </div>

        <div class="checkbox switcher visibility-toggle">
          <span>Visibility</span>
          <%= f.label :kind, for: "visibility-toggle-#{widget.id}" do %>
            <%= f.check_box :kind, {class: 'primary', id: "visibility-toggle-#{widget.id}" }, "visible", "hidden"  %>
            <span><small></small></span>
            <small></small>
          <% end %>
        </div>

      </div>
      <div class="modal-footer">
        <%= submit_tag "SAVE", class: 'btn btn-primary btn-block' %>
      </div>
    <% end %>
  </div>
</div>

app/views/widgets/_widget.html.erb
<div class="col-4 p-2">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title"><%= widget.name %></h5>
      <h6 class="card-subtitle mb-2 text-muted">
        Author:
        <% if logged_in? %>
          <%= link_to widget.user.full_name, user_path(widget.user.id) %>
        <% else %>
          <%= widget.user.full_name %>
        <% end %>
      </h6>
      <p class="card-text"><%= widget.description %></p>

      <p class="card-text"><small class="text-muted">
        <strong>Visibility: </strong> <%= widget.kind %>
      </small></p>
    </div>
    <div class="card-footer">
      <% if widget.owner %>
        <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#widget-edit-modal-<%= widget.id %>">
          EDIT
        </button>
        <div class="modal fade" id="widget-edit-modal-<%= widget.id %>" tabindex="-1" role="dialog" aria-labelledby="widget-edit-modal-<%= widget.id %>" aria-hidden="true">
          <%= render partial: 'form', locals: {widget: widget} %>
        </div>

        <%= link_to user_widget_path(current_user.id, widget.id),
                    method: :delete, class: 'btn btn-danger float-right',
                    data: { confirm: "Permanently delete widget ?" } do %>
          <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="trash-alt" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" height="16px" width="16px" class="svg-inline--fa fa-trash-alt fa-w-14 fa-5x danger">
            <path fill="currentColor" d="M32 464a48 48 0 0 0 48 48h288a48 48 0 0 0 48-48V128H32zm272-256a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zm-96 0a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zm-96 0a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zM432 32H312l-9.4-18.7A24 24 0 0 0 281.1 0H166.8a23.72 23.72 0 0 0-21.4 13.3L136 32H16A16 16 0 0 0 0 48v32a16 16 0 0 0 16 16h416a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16z" class=""></path>
          </svg>
        <% end %>

      <% end %>
    </div>
  </div>

</div>

app/views/widgets/create.js.erb
<%= make_js_flashes @error, @messages %>
<% unless @error %>
$('#modal').modal('hide')
<% end %>

app/views/widgets/index.html.erb
<div class="widgets-index row">

  <%= render 'shared/search_bar' %>
  <div class="col-12">
    <div class="row">
      <%= render partial: "widget", collection: @widgets %>
    </div>
  </div>
</div>

app/views/widgets/new.js.erb
var elem = $('#modal');
elem.html( "<%= j render 'form' %>")
elem.modal()

app/views/widgets/update.js.erb
<%= make_js_flashes @error, @messages %>
<% unless @error %>
location.reload()
<% end %>